### ISSUE TITLE
[BUG] Unintentional Phone Tapping

### ISSUE THREAD

**Issue by PerfectLies86** [dennrick/LineageRoleplay#106] opened 2021-05-25 05:44 UTC
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

When I get off the phone with someone there are times that the radio seems to stick on the radio channel for the phone call and the person on the other end of the line can hear your proximity conversations or I can hear theirs.

**To Reproduce** *(Steps to reproduce the behavior):*
  

1. Join Random radio channel just to see if this works
2. Call someone and have a nice conversation
3. Hang up phone and look in top left corner to see if you switched back to original radio channel. (probably not)
4. Listen for other person's convo or wait for them to call you back because they can hear yours.

**Expected behavior** *(A clear and concise description of what you expected to happen):*

Hang up the call and I don't have to talk to them anymore unless I want to.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
I did not think of this until after I was offline, so I don't know if there were any F8 errors. I can try to reproduce again if needed.
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by daddyDUBZ** [comment] 2021-06-14 17:32
After call the phone call station disconnects now, but radio doesn't reconnect after call.  By design? @dennrick @MjrDeathAdder

**Comment by dennrick** [comment] 2021-06-14 17:52
@GradientWizzard

**Comment by GradientWizzard** [comment] 2021-06-14 18:09
Due to the fact its using removePlayerFromAllRadio it'll drop both radio and phone will push an update for this

**Comment by daddyDUBZ** [comment] 2021-06-17 17:30
@GradientWizzard 

NEW TICKET ON OPEN ISSUE

[8:47 AM] sharkriot: So I had an interesting experience where after a phone call ended, if caps lock was held, the recipients could still talk to each other
[8:48 AM] sharkriot: I can grab a clip of it in the morning
[10:28 AM] daddyDUBZ: Cool man thanks for submitting the issue.  We are aware of this one and there is a ticket on github for it. ill drop a link here momentarily

**Comment by dennrick** [comment] 2021-06-29 07:06
This has been resolved with the latest switch to pma-voice

**Closed by dennrick** 2021-06-29 07:06 UTC
Labels: bug
